### ISSUE TITLE
package create command fails

### ISSUE THREAD

**Issue by iancoffey** [coreos/updateservicectl#107]
When trying to create a package as per the docs, the command fails with ``Error 400: : Could not validate the package.`` Ive tried the latest 3 versions of updateservicectl, same deal with each.

```
$ updateservicectl package create --app-id=83056c87-18ed-4762-8918-3628a68ded11 --version==0.0.1 --file=fake-0.0.1.tar.gz
{
 "sha1Sum": "7ddAacIrVyg/JtxynWzP4j4O7Bs=",
 "sha256Sum": "xCopwLKiU1JbTQQaoXghGM8Z3NG10Sbedo7c8v5HCcY=",
 "size": "170"
}
2015/05/21 10:41:13 googleapi: Error 400: : Could not validate the package.
```

**Comment by sym3tri** [comment]
Apologies for the confusion. This is a bug with the `package create` command. It should require the `--url` flag and print a more descriptive message if it is not provided.

The URL should be the location of payload (i.e. something like `--url="http://my-s3-bucket-or-fileserver.com/my-app/0.0.1/fake-0.0.1.tar.gz"`).

Note that `package create` only adds an entry to the CoreUpdate database and does not actually upload or serve the file. If you want to also serve the file via CoreUpdate (only available for on-premise deployments) see the `updateservicectl package upload` command along with the CoreUpdate config options: `enable-package-uploads` and `static-packages-dir` which are [documented here](https://github.com/coreos/updateservicectl/blob/master/Documentation/on-premise-deployment.md#configuration-file).

**Comment by iancoffey** [comment]
Thanks for the answer! I tried package created with --url and with and without --file, seems like I might be missing something.

```
$ updateservicectl package create --app-id=83056c87-18ed-4762-8918-3628a68ded11 --version==0.0.1 --url=https://s3.amazonaws.com/rg123/fake-0.0.1.tar.gz
2015/05/21 15:14:42 stat of  failed: stat : no such file or directory

$ updateservicectl package create --app-id=83056c87-18ed-4762-8918-3628a68ded11 --version==0.0.1 --url=https://s3.amazonaws.com/rg123/fake-0.0.1.tar.gz --file=fake-0.0.1.tar.gz
{
 "sha1Sum": "7ddAacIrVyg/JtxynWzP4j4O7Bs=",
 "sha256Sum": "xCopwLKiU1JbTQQaoXghGM8Z3NG10Sbedo7c8v5HCcY=",
 "size": "170",
 "url": "https://s3.amazonaws.com/rg123/fake-0.0.1.tar.gz"
}
2015/05/21 15:14:44 googleapi: Error 400: : Could not validate the package.
```

**Comment by sym3tri** [comment]
You will need both --url and --file.
Having two equal signs in your version flag `--version==0.0.1` would cause an error.

**Comment by iancoffey** [comment]
Thanks and sorry for the oversight. Maybe this is useful? https://github.com/coreos/updateservicectl/pull/108

Thanks again.

**Comment by nikhleshgoenka** [comment]
Make sure --version doesn't have more than 2 dots.

Example: 0.11.2.250-6 will not work, whereas 0.11.2-250.6 would work.
